### ISSUE TITLE
Create a github release in mento-sdk

### ISSUE THREAD

**Issue by bowd** [mento-protocol/mento-sdk#8] opened 2023-02-10 15:35 UTC
**Description**

Create the first GitHub release in mento-core repo. [Release and versioning guide](https://www.notion.so/Release-process-and-versioning-78bd7021a39a4fdf8e7495174a19d676#fc8d42ecbd5b401ea343d27d36e142b5) for reference.

**Acceptance Criteria**

- [ ] First version of mento-sdk is released
- [ ] The tag corresponds to v0.1.0

**Comment by bayological** [comment] 2023-02-22 01:13
Closing this as it's a duplicate of #4

**Closed by bayological** 2023-02-22 01:13 UTC
